apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: retail-pvc
  namespace: re-ns
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: fitness-sc
  resources:
    requests:
      storage: 2Gi